export const WEAK_PASSWORD_SCORE_THRESHOLD = 2;
export const MEDIUM_PASSWORD_SCORE_THRESHOLD = 4;
export const MIN_PASSWORD_LENGTH = 8;

export const MIN_AGE_STRING_LENGTH = 1;
export const AGE_MIN_VALUE = 0;
export const NAME_MIN_LENGTH = 1;
export const PASSWORD_MIN_LENGTH = 8;
export const KILOBYTE_TO_BYTE = 1024;
export const MEGABYTE_TO_KILOBYTE = 1024;
export const FILE_SIZE_LIMIT_MB = 2;
export const FILE_SIZE_LIMIT_BYTES =
  FILE_SIZE_LIMIT_MB * MEGABYTE_TO_KILOBYTE * KILOBYTE_TO_BYTE;
