export const NON_COUNTRY_ENTITIES = new Set([
  "Africa",
  "Africa (GCP)",
  "Asia",
  "Asia (excl. China and India)",
  "Asia (GCP)",
  "Central America",
  "Central America (GCP)",
  "Europe",
  "Europe (excl. EU-27)",
  "Europe (excl. EU-28)",
  "Europe (GCP)",
  "European Union (27)",
  "European Union (28)",
  "High-income countries",
  "International aviation",
  "International shipping",
  "International transport",
  "Least developed countries (Jones et al.)",
  "Low-income countries",
  "Lower-middle-income countries",
  "Non-OECD (GSP)",
  "North America",
  "North America (excl. USA)",
  "North America (GCP)",
  "Oceania",
  "Oceania (GCP)",
  "OECD (GSP)",
  "OECD (Jones et al.)",
  "Small island developing states",
  "South Africa",
  "South America",
  "South America (GCP)",
  "Upper-middle-income countries",
  "World",
]);

export function isCountryEntity(entityName: string): boolean {
  return !NON_COUNTRY_ENTITIES.has(entityName);
}
