#.github/workflows/format_and_lint.yml
name: Format and Lint

on:
  push:
    branches:
      - '**'

jobs:
  checks:
    name: Run ${{ matrix.task }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task: [ci:format, lint]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: npm install

      - name: Run ${{ matrix.task }}
        run: npm run ${{ matrix.task }}
